language: java

jdk:
  - oraclejdk8
    
install: true
script:
- mvn -U clean package 
  
after_success:
- mvn jacoco:report coveralls:report 
- bash <(curl -s https://copilot.blackducksoftware.com/ci/travis/scripts/upload)
